version: "3.9"

services:
  web:
    build:
      context: ./ToiletApiNew
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    env_file:
      - ./.env.prod
    command: bash -c "gunicorn ToiletApiNew.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: