# Generated by Django 3.2.4 on 2021-06-16 10:00

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_worldborder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('access_notes', models.CharField(blank=True, default='', max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('charge', models.CharField(blank=True, default='', max_length=100)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=100)),
                ('male_only', models.BooleanField(default=False)),
                ('female_only', models.BooleanField(default=False)),
                ('unisex', models.BooleanField(default=False)),
                ('baby_change', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('radar_only', models.BooleanField(default=False)),
                ('radar_available', models.BooleanField(default=False)),
                ('changing_place', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(blank=True, default='', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
            ],
        ),
    ]
