# Generated by Django 3.2.4 on 2021-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_toilet'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
