# Generated by Django 3.2.4 on 2021-06-16 15:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_toilet_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('details', models.CharField(blank=True, default='', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='toilet',
            name='num_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='toilet',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DNE', 'This toilet does not exist'), ('O', 'Other')], max_length=3)),
                ('other_description', models.TextField(blank=True, default='', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.toilet')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.toilet')),
            ],
        ),
    ]
