# Generated by Django 3.2.4 on 2021-06-17 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210616_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='suggestedtoilet',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='toilet',
            options={'ordering': ['-date_modified']},
        ),
    ]
