# Generated by Django 3.2.4 on 2021-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210617_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='access_notes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='data_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
